# Generated by Django 4.0.7 on 2023-05-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subscriber_count',
            new_name='subscribers_count',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='subscription_count',
            new_name='subscriptions_count',
        ),
    ]
